### ISSUE TITLE
Error: Call to undefined function entity_view() in template_preprocess_search_api_page_results

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/search_api_page#1]
When I try switch to a view mode like "Full Content" I get:

> Error: Call to undefined function entity_view() in template_preprocess_search_api_page_results() (line 103 of /app/modules/search_api_page/search_api_page.theme.inc).

**Comment by herbdool** [comment]
If I change it to `entity_plus_view` it all works.

**Comment by earlyburg** [comment]
Hello @herbdool -
This has been fixed with the latest release available here:
[Search API Page release 1.0.02](https://github.com/backdrop-contrib/search_api_page/releases/tag/1.x-1.0.02)
Closing this issue. Thanks for the feedback, I appreciate it.
